from app.schemas.approval import (
    ApprovalBrief,
    ApprovalCreate,
    ApprovalResponse,
    ApprovalReview,
)

# LayeredMemory schemas deleted — replaced by app.modules.memory (fish_memory system)
from app.schemas.organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationInDB,
    OrganizationListResponse,
    OrganizationSimple,
    OrganizationTree,
    OrganizationUpdate,
)
from app.schemas.permission import (
    PermissionBase,
    PermissionCreate,
    PermissionInDB,
    PermissionListResponse,
    PermissionSimple,
    PermissionTree,
    PermissionUpdate,
    RolePermissionsUpdate,
    UserPermissionsResponse,
)
from app.schemas.runner_schemas import (
    BindUserRequest,
    ConnectionEventResponse,
    DiagnosticsResponse,
    LocalLogEntry,
    LocalLogQuery,
    RotateTokenResponse,
    RunnerReleaseResponse,
    SetDefaultRunnerRequest,
)
from app.schemas.schemas import (
    AgentBase,
    AgentBrief,
    AgentCreate,
    AgentResponse,
    AgentUpdate,
    AIModelConfigBase,
    AIModelConfigCreate,
    AIModelConfigResponse,
    AIModelConfigUpdate,
    AIModelTestRequest,
    AIModelTestResponse,
    ChangePasswordRequest,
    CronJobBase,
    CronJobCreate,
    CronJobResponse,
    CronJobUpdate,
    DashboardStats,
    KnowledgeBaseBase,
    KnowledgeBaseCreate,
    KnowledgeBaseResponse,
    KnowledgeBaseUpdate,
    KnowledgeDocumentBase,
    KnowledgeDocumentCreate,
    KnowledgeDocumentResponse,
    KnowledgeDocumentUpdate,
    MessageResponse,
    PaginatedResponse,
    PasswordResetConfirmRequest,
    PasswordResetRequest,
    ProfileUpdateRequest,
    RefreshTokenRequest,
    RoleBase,
    RoleCreate,
    RoleResponse,
    RoleUpdate,
    RunnerApprove,
    RunnerBase,
    RunnerCreate,
    RunnerHeartbeat,
    RunnerResponse,
    RunnerUpdate,
    SkillBase,
    SkillBrief,
    SkillCreate,
    SkillResponse,
    SkillUpdate,
    TaskBase,
    TaskCreate,
    TaskResponse,
    TaskUpdate,
    Token,
    TokenPayload,
    UsageStats,
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)
from app.schemas.task_comment import (
    TaskCommentBase,
    TaskCommentCreate,
    TaskCommentDetail,
    TaskCommentInDB,
    TaskCommentListResponse,
    TaskCommentUpdate,
)
from app.schemas.wiki import (
    WikiBase,
    WikiCreate,
    WikiDetail,
    WikiImportRequest,
    WikiInDB,
    WikiListResponse,
    WikiSearchResponse,
    WikiSearchResult,
    WikiTree,
    WikiUpdate,
    WikiVersionInDB,
    WikiVersionListResponse,
)
from app.schemas.workspace import (
    WorkspaceBrief,
    WorkspaceCreate,
    WorkspaceResponse,
    WorkspaceSettings,
    WorkspaceSettingsUpdate,
    WorkspaceUpdate,
)

__all__ = [
    # 原有 Schema
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "RefreshTokenRequest",
    "ProfileUpdateRequest",
    "ChangePasswordRequest",
    "PasswordResetRequest",
    "PasswordResetConfirmRequest",
    "Token",
    "TokenPayload",
    "AgentBase",
    "AgentCreate",
    "AgentUpdate",
    "AgentResponse",
    "AgentBrief",
    "SkillBase",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "SkillBrief",
    "DashboardStats",
    "UsageStats",
    "RunnerBase",
    "RunnerCreate",
    "RunnerUpdate",
    "RunnerResponse",
    "RunnerApprove",
    "RunnerHeartbeat",
    "AIModelConfigBase",
    "AIModelConfigCreate",
    "AIModelConfigUpdate",
    "AIModelConfigResponse",
    "AIModelTestRequest",
    "AIModelTestResponse",
    "KnowledgeBaseBase",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "KnowledgeDocumentBase",
    "KnowledgeDocumentCreate",
    "KnowledgeDocumentUpdate",
    "KnowledgeDocumentResponse",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "CronJobBase",
    "CronJobCreate",
    "CronJobUpdate",
    "CronJobResponse",
    "PaginatedResponse",
    "MessageResponse",
    # 新增 Schema
    "OrganizationBase", "OrganizationCreate", "OrganizationUpdate", "OrganizationInDB",
    "OrganizationTree", "OrganizationSimple", "OrganizationListResponse",
    "PermissionBase", "PermissionCreate", "PermissionUpdate", "PermissionInDB",
    "PermissionTree", "PermissionSimple", "PermissionListResponse",
    "RolePermissionsUpdate", "UserPermissionsResponse",
    "WikiBase", "WikiCreate", "WikiUpdate", "WikiInDB", "WikiDetail", "WikiTree",
    "WikiVersionInDB", "WikiVersionListResponse", "WikiListResponse",
    "WikiSearchResult", "WikiSearchResponse", "WikiImportRequest",
    "TaskCommentBase", "TaskCommentCreate", "TaskCommentUpdate", "TaskCommentInDB",
    "TaskCommentDetail", "TaskCommentListResponse",
    # 分层记忆 — deleted, replaced by fish_memory system
    # Workspace + Approval
    "WorkspaceSettings",
    "WorkspaceCreate",
    "WorkspaceUpdate",
    "WorkspaceSettingsUpdate",
    "WorkspaceResponse",
    "WorkspaceBrief",
    "ApprovalCreate",
    "ApprovalReview",
    "ApprovalResponse",
    "ApprovalBrief",
    # Runner Management Enhancement
    "BindUserRequest",
    "SetDefaultRunnerRequest",
    "RotateTokenResponse",
    "DiagnosticsResponse",
    "LocalLogQuery",
    "LocalLogEntry",
    "ConnectionEventResponse",
    "RunnerReleaseResponse",
]
